CREATE TABLE model
    (
        id_modelu INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nazwa varchar(20) NOT NULL,
        marka varchar (30) NOT NULL,
        rok_produkcji NUMBER(4) NOT NULL,
        poj_silnika FLOAT NOT NULL
    );

CREATE TABLE klienci
    (
        id_klienta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        imie VARCHAR(20) NOT NULL,
        nazwisko VARCHAR(40) NOT NULL,
        pesel CHAR(11) NOT NULL,
        nip CHAR(10),
        miasto VARCHAR(50) NOT NULL,
        kod_pocztowy CHAR(7) NOT NULL,
        adres VARCHAR(50) NOT NULL,
        mail VARCHAR(70) NOT NULL,
        telefon CHAR(9) NOT NULL
    );

CREATE TABLE etaty
    (
        id_etatu INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        nazwa_etatu VARCHAR(30) NOT NULL,
        placa_pod FLOAT NOT NULL,
        placa_dod FLOAT,
        ilosc_godzin INT 
    );

CREATE TABLE oddzialy 
    (
        id_oddzialu INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	nazwa_oddzialu VARCHAR(20) NOT NULL,
        adres VARCHAR2(20) NOT NULL,
        nr_tel CHAR(9) NOT NULL,
        nr_pokoju CHAR(3) NOT NULL
    );

CREATE TABLE dzialy 
    (
        id_dzialu INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        id_oddzialu INTEGER NOT NULL,
        id_szefa INTEGER NOT NULL
    );
ALTER TABLE dzialy
ADD FOREIGN KEY (id_oddzialu) REFERENCES oddzialy(id_oddzialu);

CREATE TABLE pracownicy
    (
    id_pracownika INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_etatu INT NOT NULL,
    id_dzialu INT NOT NULL,
    imie VARCHAR(20) NOT NULL,
    nazwisko VARCHAR(50) NOT NULL,
    pesel CHAR(11) NOT NULL,
    miasto VARCHAR(50) NOT NULL,
    kod_pocztowy CHAR(7) NOT NULL,
    adres VARCHAR(70) NOT NULL,
    mail VARCHAR(70) NOT NULL,
    telefon CHAR(9) NOT NULL,
    data_zatrudnienia DATE NOT NULL,
    data_zwolnienia DATE
    );
ALTER TABLE pracownicy
ADD FOREIGN KEY (id_etatu) REFERENCES etaty(id_etatu);

ALTER TABLE pracownicy
ADD FOREIGN KEY (id_dzialu) REFERENCES dzialy(id_dzialu);



CREATE TABLE pojazdy
    (
        id_pojazdu INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_modelu INT NOT NULL,
        przebieg INT NOT NULL,
        rodzaj_pojazdu VARCHAR(30) NOT NULL,
        nr_rej CHAR(7) NOT NULL,
        nr_vin ChAR(17) NOT NULL,
        powypadkowy VARCHAR(5),
        cena_zakupu FLOAT NOT NULL,
        cena_sprzedazy FLOAT,
        data_przyjęcia DATE DEFAULT CURRENT_DATE,
        data_sprzeaży DATE,
        kolor varchar(20)     
    );
ALTER TABLE pojazdy
ADD FOREIGN KEY (id_modelu) REFERENCES model(id_modelu);

CREATE TABLE naprawy
    (
    id_naprawy INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_klienta INT NOT NULL,
    id_pracownika INT NOT NULL,
    nr_faktury CHAR(10) NOT NULL,
    opis VARCHAR(130),
    cena_czesci FLOAT,
    kwota_za_wykonanie FLOAT NOT NULL, 
    data_przyjęcia DATE DEFAULT CURRENT_DATE NOT NULL,
    data_oddanie DATE,
    sposob_zaplaty VARCHAR(30),
    czy_zaplacono CHAR(3)
    );
ALTER TABLE naprawy
ADD FOREIGN KEY (id_klienta) REFERENCES klienci(id_klienta);

ALTER TABLE naprawy
ADD FOREIGN KEY (id_pracownika) REFERENCES pracownicy(id_pracownika);

CREATE TABLE czesci
    (
       id_czesci INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
       id_naprawy INT NOT NULL,
       id_pracownika INT NOT NULL,
       nr_faktury CHAR(10) NOT NULL,
       nazwa_czesci VARCHAR(70),
       nazwa_sprzedawcy VARCHAR(50),
       nip_sprzedwacy CHAR(10)
     );
ALTER TABLE czesci
ADD FOREIGN KEY (id_naprawy) REFERENCES naprawy(id_naprawy);

ALTER TABLE czesci
ADD FOREIGN KEY (id_pracownika) REFERENCES pracownicy(id_pracownika);

CREATE TABLE tranzakcje
    (
    id_tranzakcji INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
    id_pojazdu INT NOT NULL,
    id_klienta INT NOT NULL,
    id_pracownika INT NOT NULL,
    rodzaj_tranzakcji VARCHAR(50) NOT NULL,
    kwota FLOAT NOT NULL,
    nr_faktury CHAR(10) NOT NULL,
    sposbb_platnosci VARCHAR(40),
    data_tranzakcji DATE DEFAULT CURRENT_DATE NOT NULL,
    data_zaplaty DATE,
    czy_zaplacono char(3)
    );
ALTER TABLE tranzakcje
ADD FOREIGN KEY (id_pojazdu) REFERENCES pojazdy(id_pojazdu);

ALTER TABLE tranzakcje
ADD FOREIGN KEY (id_klienta) REFERENCES klienci(id_klienta);

ALTER TABLE tranzakcje
ADD FOREIGN KEY (id_pracownika) REFERENCES pracownicy(id_pracownika);






















/*
Drop table model;
Drop table pojazdy;
Drop table czesci;
Drop table tranzakcje;
Drop table klienci;
Drop table etaty;
Drop table naprawy;
Drop table pracownicy;
drop table dzialy;
drop table oddzialy;*/